javafx:
  stage:
    resizable: false
  title: MyCoolApp

server:
  port: 0
  servlet:
    context-path: /

## Freemarker 配置
spring:
  freemarker:
    template-loader-path: classpath:/web/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

debug: false
logging:
  file:
    path: logs
#  pattern:
#    console: %d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
#    file: %d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n
